version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - lang.0.25.0
      - run:
          name: Install crystal
          command: |
            cd ..
            if [[ ! -d crystal-0.25.0-1 ]]; then wget https://github.com/crystal-lang/crystal/releases/download/0.25.0/crystal-0.25.0-1-linux-x86_64.tar.gz && tar xvfz crystal-0.25.0-1-linux-x86_64.tar.gz; fi
      - save_cache:
          key: lang.0.25.0
          paths:
            - ../crystal-0.25.0-1/

      - restore_cache:
          keys:
            - libs-{{ checksum "shard.lock" }}
      - run:
          name: Install shards
          command: |
            ../crystal-0.25.0-1/bin/shards check || ../crystal-0.25.0-1/bin/shards
      - save_cache:
          key: libs-{{ checksum "shard.lock" }}
          paths:
            - lib/

      - run:
          name: Run specs
          command: ../crystal-0.25.0-1/bin/crystal spec
